export const COLORS = {
  CHECK_IN: 0x00FF00,
  CHECK_OUT: 0xFF0000,
  LEAVE_PENDING: 0xFFA500,
  LEAVE_APPROVED: 0x00FF00,
  LEAVE_REJECTED: 0xFF0000,
  RESIGNATION_PENDING: 0xFFA500,
  RESIGNATION_APPROVED: 0x00FF00,
  RESIGNATION_REJECTED: 0xFF0000,
} as const;

export const webhooks = {
  default: import.meta.env.VITE_DISCORD_WEBHOOK_URL,
  resignation: import.meta.env.VITE_DISCORD_RESIGNATION_WEBHOOK_URL,
  leave: import.meta.env.VITE_DISCORD_LEAVE_WEBHOOK_URL,
} as const;